"""add algs table

Revision ID: 6dda8f948f38
Revises: a6fc0222ab45
Create Date: 2026-04-30 15:14:25.541112

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6dda8f948f38"
down_revision: Union[str, Sequence[str], None] = "a6fc0222ab45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "algs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("algorithm_id", sa.Integer(), nullable=True),
        sa.Column("alg", sa.String(), nullable=True),
        sa.Column("is_selected", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["algorithm_id"],
            ["algorithms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("algs")
    # ### end Alembic commands ###
